speed_ = [0, 0];
gravity_ = 0.8;
move_ = 0;
alarm[0] = game_get_speed(gamespeed_fps)*5
alarm[1] = game_get_speed(gamespeed_fps)*10
jump_height_ = -20;
max_health = 100 
health_ = max_health;
flash = false;